apiVersion: v1
kind: ConfigMap
metadata:
  name: finly-frontend-config
  namespace: default
data:
  ENV: "dev"
  BACKEND_URL: "http://backend.finly.click"  # Update this to match your backend's external URL or internal service URL
