name: Docker Build, Push and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Replace image tag with Git SHA
        run: |
          sed -i "s|danyazhurba/finly-frontend:__IMAGE_TAG__|danyazhurba/finly-frontend:${{ github.sha }}|g" deployment/k8s/deployment.yaml      

      - name: Build and push Docker image for frontend
        run: |
          docker build -f deployment/Dockerfile -t finly-frontend .
          
          docker tag finly-frontend danyazhurba/finly-frontend:${{ github.sha }}
          docker tag finly-frontend danyazhurba/finly-frontend:latest

          docker push danyazhurba/finly-frontend:${{ github.sha }}
          docker push danyazhurba/finly-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push  # Залежить від виконання попереднього job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          echo "$KUBECONFIG" > kubeconfig
          export KUBECONFIG=kubeconfig

          kubectl apply -f deployment/k8s/deployment.yaml
          kubectl apply -f deployment/k8s/ingress.yaml
          kubectl apply -f deployment/k8s/configmap.yaml
