name: Docker Build, Push and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full repository is checked out

      - name: List repository files
        run: |
          ls -R
          ls -l deployment/Dockerfile || echo "Dockerfile not found"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image for frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployment/Dockerfile
          build-args: |
            REACT_APP_BACKEND_URL=http://backend.finly.click
          tags: |
            zhdanila/finly-frontend:${{ github.sha }}
            zhdanila/finly-frontend:latest
          push: true

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List Kubernetes manifests
        run: |
          ls -l deployment/k8s/

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          echo "$KUBECONFIG" > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl apply -f deployment/k8s/deployment.yaml
          kubectl apply -f deployment/k8s/ingress.yaml
          kubectl apply -f deployment/k8s/configmap.yaml