name: Docker Push

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t finly-frontend .
          docker tag finly-frontend danyazhurba/finly-frontend:${{ github.sha }}
          docker push danyazhurba/finly-frontend:${{ github.sha }}
          
          docker build -t finly-frontend .
          docker tag finly-frontend danyazhurba/finly-frontend:${{ github.sha }}
          docker tag finly-frontend danyazhurba/finly-frontend:latest
          docker push danyazhurba/finly-frontend:${{ github.sha }}
          docker push danyazhurba/finly-frontend:latest
        
          
